import fs from "fs";
import path from "path";
import { productCatalog } from "../shared/catalog/product-catalog";

const BASE_URL = "https://zleshop.cz";
const OUTPUT_PATH = path.resolve("client/public/sitemap.xml");

type StaticRoute = {
  path: string;
  changefreq: "weekly" | "monthly" | "yearly";
  priority: string;
};

const staticRoutes: StaticRoute[] = [
  { path: "/", changefreq: "weekly", priority: "1.0" },
  { path: "/shop", changefreq: "weekly", priority: "0.8" },
  { path: "/story", changefreq: "monthly", priority: "0.7" },
  { path: "/crew", changefreq: "monthly", priority: "0.6" },
  { path: "/contact", changefreq: "monthly", priority: "0.5" },
  { path: "/legal", changefreq: "yearly", priority: "0.3" },
  { path: "/legal/terms", changefreq: "yearly", priority: "0.2" },
  { path: "/legal/privacy", changefreq: "yearly", priority: "0.2" },
  { path: "/legal/cookies", changefreq: "yearly", priority: "0.2" },
  { path: "/legal/returns", changefreq: "yearly", priority: "0.2" },
  { path: "/legal/withdrawal", changefreq: "yearly", priority: "0.2" },
  { path: "/legal/contact", changefreq: "yearly", priority: "0.2" },
];

const productRoutes = productCatalog
  .filter((product) => product.status === "published")
  .map((product) => ({
    path: `/p/${product.id}`,
    changefreq: "weekly" as const,
    priority: "0.7",
  }));

const allRoutes = [...staticRoutes, ...productRoutes];

const urlXml = allRoutes
  .map(
    (route) => `  <url>
    <loc>${BASE_URL}${route.path}</loc>
    <changefreq>${route.changefreq}</changefreq>
    <priority>${route.priority}</priority>
  </url>`,
  )
  .join("\n");

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- AUTO-GENERATED BY script/generate-sitemap.ts. DO NOT EDIT PRODUCT URLS MANUALLY. -->
<urlset
  xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
>
${urlXml}
</urlset>
`;

fs.writeFileSync(OUTPUT_PATH, xml, "utf8");
console.log(`Generated sitemap with ${allRoutes.length} URLs at ${OUTPUT_PATH}`);
