import fs from "fs";
import path from "path";

const BASE_URL = "https://zleshop.cz";
const OUTPUT_PATH = path.resolve("client/public/sitemap.xml");
const ALLOW_STATIC_ONLY_FLAG = "--allow-static-only-on-product-source-failure";

type StaticRoute = {
  path: string;
  changefreq: "weekly" | "monthly" | "yearly";
  priority: string;
};

type SitemapRoute = {
  path: string;
  changefreq: "weekly" | "monthly" | "yearly";
  priority: string;
};

const staticRoutes: StaticRoute[] = [
  { path: "/", changefreq: "weekly", priority: "1.0" },
  { path: "/shop", changefreq: "weekly", priority: "0.8" },
  { path: "/story", changefreq: "monthly", priority: "0.7" },
  { path: "/crew", changefreq: "monthly", priority: "0.6" },
  { path: "/contact", changefreq: "monthly", priority: "0.5" },
  { path: "/legal", changefreq: "yearly", priority: "0.3" },
  { path: "/legal/terms", changefreq: "yearly", priority: "0.2" },
  { path: "/legal/privacy", changefreq: "yearly", priority: "0.2" },
  { path: "/legal/cookies", changefreq: "yearly", priority: "0.2" },
  { path: "/legal/returns", changefreq: "yearly", priority: "0.2" },
  { path: "/legal/withdrawal", changefreq: "yearly", priority: "0.2" },
  { path: "/legal/contact", changefreq: "yearly", priority: "0.2" },
];

function isProductionLikeEnvironment(): boolean {
  return String(process.env.NODE_ENV || "").toLowerCase() === "production" || String(process.env.CI || "").toLowerCase() === "true";
}

function isStaticOnlyOverrideEnabled(): boolean {
  const byFlag = process.argv.includes(ALLOW_STATIC_ONLY_FLAG);
  const byEnv = ["1", "true", "yes"].includes(String(process.env.SITEMAP_ALLOW_STATIC_ONLY_ON_PRODUCT_SOURCE_FAILURE || "").toLowerCase());
  return byFlag || byEnv;
}

function assertOverrideSafety(isEnabled: boolean): void {
  if (!isEnabled) return;

  // This override is only for local/dev workflows; production/CI must stay strict fail-closed.
  if (isProductionLikeEnvironment()) {
    throw new Error(
      `${ALLOW_STATIC_ONLY_FLAG} (or SITEMAP_ALLOW_STATIC_ONLY_ON_PRODUCT_SOURCE_FAILURE) is forbidden in production/CI environments.`,
    );
  }
}

async function getLiveProductRoutesFromStorage(): Promise<SitemapRoute[]> {
  const databaseUrl = String(process.env.DATABASE_URL || "").trim();
  if (!databaseUrl) {
    throw new Error("DATABASE_URL is required to load product routes from live catalog source.");
  }

  // Never source product routes from historical static catalog data; sitemap must match live catalog logic.
  const [{ storage }, { pool }] = await Promise.all([
    import("../server/storage"),
    import("../server/db"),
  ]);

  try {
    const products = await storage.getProducts();

    return products
      .map((product) => String(product.id || "").trim())
      .filter((id) => id.length > 0)
      .map((id) => ({
        path: `/p/${encodeURIComponent(id)}`,
        changefreq: "weekly" as const,
        priority: "0.7",
      }));
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    throw new Error(`Failed to load live products for sitemap generation: ${message}`);
  } finally {
    await pool.end();
  }
}

async function main() {
  const staticOnlyOverride = isStaticOnlyOverrideEnabled();
  assertOverrideSafety(staticOnlyOverride);

  let productRoutes: SitemapRoute[] = [];

  try {
    productRoutes = await getLiveProductRoutesFromStorage();
  } catch (error) {
    if (!staticOnlyOverride) {
      // Default is strict fail-closed: if live product source is unavailable, fail build.
      throw error;
    }

    const message = error instanceof Error ? error.message : String(error);
    console.warn(`[sitemap] Product source unavailable; generating static-only sitemap due to explicit override (${ALLOW_STATIC_ONLY_FLAG}).`);
    console.warn(`[sitemap] Source error: ${message}`);
  }

  const allRoutes = [...staticRoutes, ...productRoutes];

  const urlXml = allRoutes
    .map(
      (route) => `  <url>\n    <loc>${BASE_URL}${route.path}</loc>\n    <changefreq>${route.changefreq}</changefreq>\n    <priority>${route.priority}</priority>\n  </url>`,
    )
    .join("\n");

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- AUTO-GENERATED BY script/generate-sitemap.ts. DO NOT EDIT PRODUCT URLS MANUALLY. -->
<urlset
  xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
>
${urlXml}
</urlset>
`;

  fs.writeFileSync(OUTPUT_PATH, xml, "utf8");
  console.log(`Generated sitemap with ${allRoutes.length} URLs at ${OUTPUT_PATH}`);
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exitCode = 1;
});
